# Generated by Django 4.0.3 on 2022-08-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_rest', '0006_alter_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='parks',
            field=models.ManyToManyField(null=True, related_name='Accounts', to='users_rest.parkvo'),
        ),
    ]
