# Generated by Django 4.0.3 on 2022-08-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_rest', '0010_alter_account_parks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkvo',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='parkvo',
            name='state',
            field=models.CharField(max_length=250),
        ),
    ]
