# Generated by Django 4.0.3 on 2022-08-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_rest', '0011_alter_parkvo_name_alter_parkvo_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkvo',
            name='parks_visited',
        ),
    ]
