# Generated by Django 4.0.3 on 2022-07-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks_rest', '0002_alter_park_contact_num_alter_park_entrance_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='state',
            field=models.CharField(max_length=25),
        ),
    ]
